name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-parallel: 1
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build

  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2

      - name: Run a Script
        run: echo "Compile"
             ls -a
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a Test Script
        run: gradle test

  Assemble:
    runs-on: ubuntu-latest
    steps:
      - name: Run a Script
        run: echo "Assemble"