name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build

  Compile:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Run a Script
        run: echo "Compile"
             ls -a
  Test:
    needs: [Compile]
    runs-on: ubuntu-latest
    steps:
      - name: Run a Test Script
        run: gradle test

  Assemble:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - name: Run a Script
        run: echo "Assemble"