name: Java CI

on:
  push:
    tags:
      - 'v*.*'

jobs:

  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew clean compileJava compileTestJava -i


  Test:
    needs: [Compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run a Test Script
        run: ./gradlew clean test -i
      - uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: /home/runner/work/st_nycu_lab4_309551108/st_nycu_lab4_309551108/build/test-results/test
  Assemble:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run a Assemble Script
        run: ./gradlew clean assemble -i
      - uses: actions/upload-artifact@v2
        with:
          name: buildJar
          path: /home/runner/work/st_nycu_lab4_309551108/st_nycu_lab4_309551108/build/libs/*.jar

  Release:
    needs: [Assemble]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Generate Changelog
        run: echo "good thing appear" > ${{ github.workflow }}-CHANGELOG.txt

      - name: Run a Release Script
      - uses: softprops/action-gh-release@v1
        if: startWith(github.ref, 'refs/tafs/v')
        with:
          body_path: ${{ github.workflow }}-CHANGELOG.txt
          files: |
            /home/runner/work/st_nycu_lab4_309551108/st_nycu_lab4_309551108/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
        run: echo "Release?"
